### ISSUE TITLE
[Suggestion] Specify Case sensitivity

### ISSUE THREAD

**Issue by RSYN** [CaptainPicarl/PartSwapperPublic#1]
When programs asks for 'C' to continue,   can it be made to accept either upper or lower case?  Otherwise perhaps make it clear to the user that the program is case sensitive, and they should learn to embrace that.

**Comment by CaptainPicarl** [comment]
Addressed in [release 0.0.3](https://github.com/CaptainPicarl/PartSwapperPublic/releases/tag/beta-v0.0.3)
