### ISSUE TITLE
[Bug] Duplicate subsystem listings

### ISSUE THREAD

**Issue by RSYN** [CaptainPicarl/PartSwapperPublic#2]
Examples below:  Subsystem listings seem to repeat.   This seems to apply to all system choices.   

Found block type LargeBlockLargeHydrogenThrust on your ship! Eligible for replacement!
We will be swapping out the following parts. Please select the category of parts you DO NOT WANT TO SWAP!
When finished, type 'C' to continue...
0 - LargeBlockLargeHydrogenThrust
C
0 - LargeBlockLargeHydrogenThrust
1 - LargeBlockLargeHydrogenThrust2x
2 - LargeBlockLargeHydrogenThrust4x
3 - LargeBlockLargeHydrogenThrust8x
4 - LargeBlockLargeHydrogenThrustIndustrial
5 - LargeBlockLargeHydrogenThrustIndustrial2x
6 - LargeBlockLargeHydrogenThrustIndustrial4x
7 - LargeBlockLargeHydrogenThrustIndustrial8x
8 - LargeBlockLargeHydrogenThrust
9 - LargeBlockLargeHydrogenThrust2x
10 - LargeBlockLargeHydrogenThrust4x
11 - LargeBlockLargeHydrogenThrust8x
12 - LargeBlockLargeHydrogenThrustIndustrial
13 - LargeBlockLargeHydrogenThrustIndustrial2x
14 - LargeBlockLargeHydrogenThrustIndustrial4x
15 - LargeBlockLargeHydrogenThrustIndustrial8x
What should we replace LargeBlockLargeHydrogenThrust with?

||||||

Found block type LargeJumpDrive8x on your ship! Eligible for replacement!
We will be swapping out the following parts. Please select the category of parts you DO NOT WANT TO SWAP!
When finished, type 'C' to continue...
0 - LargeJumpDrive8x
C
0 - LargeJumpDrive
1 - LargeJumpDrive2x
2 - LargeJumpDrive4x
3 - LargeJumpDrive8x
4 - LargeJumpDrive
5 - LargeJumpDrive2x
6 - LargeJumpDrive4x
7 - LargeJumpDrive8x
What should we replace LargeJumpDrive8x with?

**Comment by CaptainPicarl** [comment]
Should be resolved as of [release 0.0.4](https://github.com/CaptainPicarl/PartSwapperPublic/releases/tag/beta-v0.0.4)
