### ISSUE TITLE
[Suggestion] BP selection

### ISSUE THREAD

**Issue by RSYN** [CaptainPicarl/PartSwapperPublic#3]
Program automatically loads the first BP folder it finds.  Upon completion of edit,  and program claims "Quitting!"   It auto loads the next BP in the folder.

If possible,  it would make sense for the program to identify a list of BP's available to edit, and allow the user to choose which to load.   This would allow the user to have multiple BP's in the directory for easy on the fly edits,  instead of having to manually sort by priority.

**Comment by CaptainPicarl** [comment]
Addressed in [release 0.0.3](https://github.com/CaptainPicarl/PartSwapperPublic/releases/tag/beta-v0.0.3)
